[package]
name = "birdcage"
version = "0.1.0"
description = "Cross-platform embeddable sandbox"
authors = ["Phylum, Inc. <engineering@phylum.io>"]
rust-version = "1.63.0"
license = "LGPL-3.0"
edition = "2021"

[dependencies]
landlock = { git = "https://github.com/cd-work/rust-landlock" }

[dev-dependencies]
clap = { version = "3.2.17", features = ["derive"] }
tempfile = "3.3.0"
